services:
    sonar_badge_displayer:
        container_name: sonar_badge_displayer
        build: .
        restart: unless-stopped
        ports:
            - ${PORT}:${PORT}
        env_file:
            - .env
        environment:
            HOST: "0.0.0.0"
        networks:
            - app_network

networks:
    app_network:
        external: true
